### ISSUE TITLE
Examples from vue-ts is not working

### ISSUE THREAD

**Issue by grasulkhuja** [ycs77/headlessui-float#42]
**Versions**
 - Headless UI: v1.7.5
 - Headless UI Float: v0.10.1
 - Framework: [vue v3.2.45]
 - Browser: doesn't matter

**Describe the bug**
Examples from vue-ts not working for combobox.

**To Reproduce**
Please provide a minimal reproducible example (like github repo, codesandbox, stackblitz...), and steps to reproduce the behavior:
1. Go to [Stackblitz](https://stackblitz.com/github/ycs77/headlessui-float/tree/main/examples/example-vue-ts)
2. Scroll down to combobox example

**Expected behavior**
In listbox select component 'float ui' working works as it should, however same thing doesn't work autocomplete (Combobox options always appears below).

**Comment by ycs77** [comment]
Hi @grasulkhuja, I think this is not a bug😅, because the `<Listbox>` has set the `flip` prop and `<Combobox>` no setting. Of course, this can be misleading, I will refactor the examples later when I have time.

Also, you can set it if you want to use `<Combobox>` with `flip`, usage see: https://headlessui-float.vercel.app/vue/floatingui-options.html#flip
